var landmarks = [
	// Bucharest Landmarks
	"arch-of-triumph",
	"romanian-athenaeum",
	"palace-of-parliament",
	"national-museum-of-arts",
	"intercontinental",
	"university-square",
	"coltea-hospital",
	"national-theatre",
	"house-of-the-free-press",
	"national-arena",
	"fire-tower",
	"cotroceni-palace",
	"romanian-peasant-museum",
	"victory-palace",
	"palace-of-justice",
	"cec-palace",
	// Iasi Landmarks
	"palace-of-culture",
	"metropolitan-cathedral",
	"golia-monastery",
	"iasi-national-theatre",
	"roznovanu-palace",
	"iasi-university",
	"central-university-library",
	// Constanta Landmarks
	"tomis-harbor",
	"pp-cathedral",
	"constanta-mosque",
	"constanta-museum",
	"constanta-casino",
	"saint-mina-church",
	// Sighisoara Landmarks
	"clock-tower",
	"church-on-the-hill",
	"monastery-church",
	"saint-joseph-church",
	"holy-trinity-church",
	// Timisoara Landmarks
	"union-square",
	"saint-george-cathedral",
	"dicasterial-palace",
	"baroque-palace",
	"cetate-synagogue",
	"timisoara-national-opera",
	"huniade-castle",
	"timisoara-orthodox-cathedral",
	"millenium-church",
]